### ISSUE TITLE
Automatically detect Timezone

### ISSUE THREAD

**Issue by lindseydiloreto** [blue-mantis/BM-Time-Ago-In-Words#3]
Nice plugin, this is really helpful!

It would be great if the plugin could automatically guess the Timezone. That information is readily available via PHP, but a pain to look up when you install the plugin.

**Comment by auralon** [comment]
This is certainly something we could look to implement, at the moment is defaults to `Europe/London`.

I'm quite busy at the moment, but leave it with me!  (Also accepting pull requests, if you want to make the changes! :+1: )
